### ISSUE TITLE
Add prettier

### ISSUE THREAD

**Issue by zaki-yama** [zaki-yama/redux-express-template#16]
https://prettier.io/

**Comment by zaki-yama** [comment]
https://github.com/sbdchd/neoformat

**Comment by zaki-yama** [comment]
### Vim+ALE でファイル保存時にPrettierを実行するには

* neoformat もあったけど、 ALE にも lint だけじゃなくてコードのフォーマット（fixing）機能があった
    * https://prettier.io/docs/en/vim.html#ale
    * https://github.com/w0rp/ale#2ii-fixing


```toml
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_fixers = {}
let g:ale_fixers['javascript'] = ['prettier-eslint']

# ファイル保存時に実行
let g:ale_fix_on_save = 1

# ローカルの設定ファイルを考慮する
let g:ale_javascript_prettier_use_local_config = 1
'''
```

* また、ESLint と組み合わせる場合は prettier-eslint, prettier-eslint-cli が必要
    * [prettierの使い方 - Qiita](https://qiita.com/kiida/items/405bb07c4b52bfee0219#eslint%E3%81%A8%E5%90%88%E3%82%8F%E3%81%9B%E3%81%A6%E4%BD%BF%E3%81%86)
